import "./globals.css";

import { Auth0Provider } from "@auth0/nextjs-auth0/client";
import type { Metadata } from "next";
import { Manrope } from "next/font/google";

import { auth0 } from "@/lib/auth0";

import PageLayout from "./components/page-layout";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth0.getSession();

  return (
    <html lang="en" className={`${manrope.variable} h-full antialiased`}>
      <body>
        <Auth0Provider user={session?.user}>
          <PageLayout>{children}</PageLayout>
        </Auth0Provider>
      </body>
    </html>
  );
}
